#!/usr/bin/env escript

%% Put this file in .emacs.d
-export([main/1]).

main([File_Name]) ->
    Includes = case filelib:is_dir("../deps") of
                   false ->
                       [{i, "../include"}];
                   true ->
                       {ok, Deps} = file:list_dir("../deps"),
                       [{i, "../include"}| [{i,Di} || D <- Deps,
                              begin
                                  Di = "../deps/"++D++"/include",
                                  filelib:is_dir(Di)
                              end]]
               end,

    %% TODO: this should be cleaned up and some checking should be done before
    %% including ../../../ stuff
    IncludesAllApps = [{i, "../.."}, {i, "../../../deps"} | Includes],
    compile:file(File_Name, [warn_obsolete_guard, warn_unused_import,
                             warn_shadow_vars, warn_export_vars,
                             strong_validation, report | IncludesAllApps]).

